version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.14.2
      - image: trufflesuite/ganache-cli
        command: ganache-cli

    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install project dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/
            - node_modules/
      - run:
          name: Link packages
          command: yarn bootstrap
      - run:
          name: Compile code
          command: yarn build
      - run:
          name: Do unit tests
          command: yarn test
      - run:
          name: Check code style
          command: yarn lint
      - run:
          name: Report code coverage
          command: yarn ci:coverage

workflows:
  version: 2
  code-quality:
    jobs:
        - test
